import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // FTC Resource sidebar with organized structure
  ftcSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/team-handbook',
        'getting-started/ftc-basics',
        'getting-started/safety',
      ],
    },
    {
      type: 'category',
      label: 'Programming',
      items: [
        'programming/index',
        // Add more programming topics as needed
      ],
    },
    {
      type: 'category',
      label: 'Building & Design',
      items: [
        'building/index',
        // Add more building topics as needed
      ],
    },
    {
      type: 'category',
      label: 'Strategy & Scouting',
      items: [
        'strategy/index',
        // Add more strategy topics as needed
      ],
    },
    {
      type: 'category',
      label: 'Engineering Notebook',
      items: [
        'notebook/index',
        // Add more notebook topics as needed
      ],
    },
    {
      type: 'category',
      label: 'Rules & Updates',
      items: [
        'rules-updates/index',
        // Add more rules topics as needed
      ],
    },
  ],

  // Alternative: Auto-generated sidebar (uncomment to use)
  // ftcSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
